### ISSUE TITLE
[Feat] 회원가입Panel 구현

### ISSUE THREAD

**Issue by YoungsonMan** [KimSesame/Project_M#16]
## 개발요소
* BaseUI_Script 로 UI관리 할 예정.
- 회원가입
    - 회원가입창 [UI_Panel/Image]
    - 취소버튼 [Button]
    - 가입버튼 [Button]
    - 이메일텍스트 [TMP_Text] 
    - 비밀번호텍스트 [TMP_Text]
    - 이메일기입란 [TMP_InputField]
    - 비밀번기입란 [TMP_InputField]

## 진행상황
- [x] 회원가입창 [UI_Panel/Image]
- [x] 취소버튼 [Button]
- [x] 가입버튼 [Button]
- [x] 이메일텍스트 [TMP_Text] 
- [x] 비밀번호텍스트 [TMP_Text]
- [x] 이메일기입란 [TMP_InputField]
- [x] 비밀번기입란 [TMP_InputField]
- [x] SignUpPanel : BaseUI 스크립트 사용, UI들 연결

**Comment by YoungsonMan** [comment]
### 일단 가입은 되는데 뭔가 빠뜨렸나 이메일 인증창이 안뜸 (만들긴 했는데안나옴).
![Image](https://github.com/user-attachments/assets/453134ba-e169-47f3-aeb5-f0560ded191d)

**Comment by YoungsonMan** [comment]
![Image](https://github.com/user-attachments/assets/d6579d71-7d96-4d3b-b637-e826059234d8)

### TODO 해놓고 안해놨었음. 이제 잘 됨
